### ISSUE TITLE
Good framework.. 

### ISSUE THREAD

**Issue by Marlysson** [AsgardIO/Thor#1]
I was take a look in you project and seems so good to work with it

Are they have some roadmap of features to include in project that accepts colaboration?

*There are some exemples of usage?*

**Comment by BTaskaya** [comment]
Sorry for delay, this framework is working but ot of date (It is to minimal for daily usage). I am working on writing new Edition of Thor.
It is completly diffrent framework and it has better structre, WSGI support etc.
In this weekend i can push base of New Edition
